services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - proxy

volumes:
  caddy_data:
    external: true
    name: caddy_caddy_data
  caddy_config:
    external: true
    name: caddy_caddy_config

networks:
  proxy:
    external: true
