name: Trigger Portainer redeploys

on:
  push:
      branches: [main]

jobs:
  changes:
      runs-on: ubuntu-latest
      outputs:
        caddy: ${{ steps.filter.outputs.caddy }}
      steps:
        - uses: actions/checkout@v4
        - uses: dorny/paths-filter@v3
          id: filter
          with:
            filters: |
              caddy:
                - 'caddy/**'
  redeploy-caddy:
    needs: changes
    if: needs.changes.outputs.caddy == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST "${{ secrets.PORTAINER_WEBHOOK_CADDY }}"
